name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Install rsync
        run: |
          choco install rsync
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: buildbranch
          folder: build
        # run: |
        #   git config --global user.email "janisflores360@gmail.com"
        #   git config --global user.name "Hunter-janis"
        #   git checkout --orphan  buildbranch
        #   del /s /q *.
        #   git commit -m "Remove old build files"
        #   git push origin buildbranch --force-with-lease
        #   git checkout master
        #   xcopy /e /i build/. .
        #   git add -A
        #   git commit -m "Deploy to GitHub Pages"
        #   git push origin master